battleship_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^battleship_viewer/', include('battleship_viewer.urls'))
]

battleship_viewer/urls.py
from django.conf.urls import url
from battleship_viewer.views import HomeView, ImportObserverLogView, GameView, GameDetailView, MoveView, MoveDetailView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^import_observer_log/$', ImportObserverLogView.as_view(), name='import_observer_log'),
    url(r'^game/$', GameView.as_view(), name='list_games'),
    url(r'^game/(?P<pk>\d+)/$', GameDetailView.as_view(), name='game-detail'),
    url(r'^game/(\d+)/move/$', MoveView.as_view(), name='list_moves'),
    url(r'^game/(?P<game>\d+)/(?P<move>\d+)/$', MoveDetailView.as_view(), name='move-detail'),
]

battleship_viewer/models.py
from django.db import models
from django.db.models import Max, Count


########################################################################
class CellState:
    EMPTY = "empty"
    JUST_MISSED = "just_missed"
    MISS = "miss"
    JUST_HIT = "just_hit"
    HIT = "hit"
    SHIP_TOP = "ship_top"
    SHIP_BOTTOM = "ship_bottom"
    SHIP_LEFT = "ship_left"
    SHIP_RIGHT = "ship_right"
    SHIP_MIDDLE = "ship_middle"


#######################################################################
class Player(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return unicode(self.name)


#######################################################################
class Game(models.Model):
    player1 = models.ForeignKey(Player, related_name="player1")
    player2 = models.ForeignKey(Player, related_name="player2")
    grid_width = models.IntegerField()
    grid_height = models.IntegerField()
    winner = models.ForeignKey(Player, null=True, related_name="winner")
    observer_log = models.TextField()

    def get_player_by_name(self, name):
        if self.player1.name == name:
            return self.player1
        elif self.player2.name == name:
            return self.player2
        else:
            raise NameError

    def get_other_player(self, player):
        if self.player1 == player:
            return self.player2
        elif self.player2 == player:
            return self.player1

    def get_next_move(self):
        highest_move = self.move_set.aggregate(Max('order'))['order__max']
        if not highest_move:
            highest_move = 0
        return Move.objects.create(game=self, order=highest_move+1)

    def num_ships_per_player(self):
        return self.ship_set.count() / 2

    def num_shots(self):
        return self.move_set.aggregate(Count('shot'))['shot__count']

    def get_player1_ship_locations(self):
        return ShipLocation.objects.filter(ship__game=self, ship__player=self.player1).values_list('x', 'y')

    def get_player2_ship_locations(self):
        return ShipLocation.objects.filter(ship__game=self, ship__player=self.player2).values_list('x', 'y')

    def __unicode__(self):
        return u'Game %s: %s vs %s' % (self.id, self.player1, self.player2)


#######################################################################
class Ship(models.Model):
    game = models.ForeignKey(Game)
    player = models.ForeignKey(Player)

    def add_location(self, x, y):
        ShipLocation.objects.create(ship=self, x=x, y=y)

    def __unicode__(self):
        return u'Game %s Player %s Ship' % (self.game.id, self.player)


########################################################################
class ShipLocationManager(models.Manager):
    ####################################################################
    def player_locations(self, game, player):
        return self.get_queryset().filter(ship__game=game, ship__player=player)


########################################################################
class ShipLocation(models.Model):
    ship = models.ForeignKey(Ship)
    x = models.IntegerField()
    y = models.IntegerField()
    objects = ShipLocationManager()

    ####################################################################
    def get_position(self):
        ship_coords = [(sl.x, sl.y) for sl in self.ship.shiplocation_set.all()]
        up = (self.x, self.y-1) in ship_coords
        down = (self.x, self.y+1) in ship_coords
        left = (self.x-1, self.y) in ship_coords
        right = (self.x+1, self.y) in ship_coords
        if (up and down) or (left and right):
            return CellState.SHIP_MIDDLE
        elif up:
            return CellState.SHIP_BOTTOM
        elif down:
            return CellState.SHIP_TOP
        elif left:
            return CellState.SHIP_RIGHT
        else:
            return CellState.SHIP_LEFT

    ####################################################################
    def __unicode__(self):
        return u'%s: %s, %s' % (self.ship, self.x, self.y)


#######################################################################
class Move(models.Model):
    game = models.ForeignKey(Game)
    player1_text = models.CharField(max_length=100)
    player2_text = models.CharField(max_length=100)
    order = models.IntegerField(db_index=True)

    def add_player_text(self, player, data):
        data = "|" + "|".join(data) + "|"
        if player == self.game.player1:
            self.player1_text = data
            self.save(update_fields=["player1_text"])
        else:
            self.player2_text = data
            self.save(update_fields=["player2_text"])

    def add_shot(self, player, x, y):
        Shot.objects.create(move=self, player=player, x=x, y=y)

    def get_previous_move_order(self):
        try:
            return Move.objects.get(game=self.game, order=self.order-1).order
        except Move.DoesNotExist:
            return 0

    def get_next_move_order(self):
        try:
            return Move.objects.get(game=self.game, order=self.order+1).order
        except Move.DoesNotExist:
            return None

    def get_player1_shots_so_far(self):
        return self.get_player_shots_so_far(self.game.player1)

    def get_player2_shots_so_far(self):
        return self.get_player_shots_so_far(self.game.player2)

    def get_player_shots_so_far(self, player):
        return Shot.objects.filter(move__game=self.game,
                                   move__order__lte=self.order,
                                   player=player).values_list('x', 'y')

    def get_state(self, player, x, y):
        ship_location = ShipLocation.objects.filter(ship__player=player, ship__game=self.game, x=x, y=y).first()
        opponent = self.game.get_other_player(player)
        if Shot.objects.filter(move=self, player=opponent, x=x, y=y).exists():
            if ship_location:
                return CellState.JUST_HIT
            else:
                return CellState.JUST_MISSED
        elif (x, y) in self.get_player_shots_so_far(opponent):
            if ship_location:
                return CellState.HIT
            else:
                return CellState.MISS
        else:
            if ship_location:
                return ship_location.get_position()
            else:
                return CellState.EMPTY

    def __unicode__(self):
        return u'%s - Move %s' % (self.game, self.order)

    class Meta:
        ordering = ['order']


#######################################################################
class Shot(models.Model):
    move = models.ForeignKey(Move)
    player = models.ForeignKey(Player)
    x = models.IntegerField()
    y = models.IntegerField()

    def __unicode__(self):
        return u'%s Player %s Shot %s, %s' % (self.move, self.player, self.x, self.y)

battleship_viewer/forms.py
from django import forms

class ImportObserverLogForm(forms.Form):
    observer_log = forms.FileField()

battleship_viewer/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, FormView, ListView, DetailView
from battleship_viewer.forms import ImportObserverLogForm
from battleship_viewer.models import Game, Move, ShipLocation, CellState, Shot
from battleship_viewer.observer_import_utils import import_game_from_file
import battleship_viewer.profiler
import time

########################################################################
class HomeView(TemplateView):
    template_name = "battleship_viewer/home.html"


########################################################################
class ImportObserverLogView(FormView):
    template_name = 'battleship_viewer/import_observer_log.html'
    form_class = ImportObserverLogForm
    success_url = '/battleship_viewer/game/'

    def form_valid(self, form):
        import_game_from_file(form.cleaned_data['observer_log'])
        return super(ImportObserverLogView, self).form_valid(form)


########################################################################
class GameView(ListView):
    model = Game


########################################################################
class GameDetailView(DetailView):
    model = Game


########################################################################
class MoveView(ListView):
    model = Move

    def get_queryset(self):
        self.game = get_object_or_404(Game, pk=self.args[0])
        return Move.objects.filter(game=self.game)

    def get_context_data(self, **kwargs):
        context = super(MoveView, self).get_context_data(**kwargs)
        context['game'] = self.game
        return context


########################################################################
class MoveDetailView(DetailView):
    model = Move

    ####################################################################
    def get_object(self, queryset=None):
        self.order = int(self.kwargs['move'])
        if self.order == 0:
            self.first_run = True
            return Move.objects.get(game=self.kwargs['game'], order=1)
        else:
            self.first_run = False
            return Move.objects.get(game=self.kwargs['game'], order=self.order)

    ####################################################################
    # @battleship_viewer.profiler.profile("move-detail")
    def get_context_data(self, **kwargs):
        context = super(MoveDetailView, self).get_context_data(**kwargs)
        move = self.get_object()
        game = move.game
        context['game'] = game
        context["player1_name"] = game.player1.name
        context["player2_name"] = game.player2.name
        if self.first_run:
            context["move_label"] = unicode(game)
            context['previous_move'] = None
            context['next_move'] = 1
            context["player1_grid"] = self.get_starting_grid(game, game.player1)
            context["player2_grid"] = self.get_starting_grid(game, game.player2)
            context["player1_shots"] = ""
            context["player2_shots"] = ""
        else:
            context["move_label"] = unicode(move)
            context['previous_move'] = move.get_previous_move_order()
            context['next_move'] = move.get_next_move_order()
            context["player1_grid"] = self.get_player_grid(move, game.player1)
            context["player2_grid"] = self.get_player_grid(move, game.player2)
            context["player1_shots"] = move.player1_text
            context["player2_shots"] = move.player2_text
        return context

    ####################################################################
    def get_starting_grid(self, game, player):
        grid = []
        ship_locations = {(sl.x, sl.y): sl for sl in ShipLocation.objects.player_locations(game, player)}
        for y in range(game.grid_height):
            row = []
            for x in range(game.grid_width):
                if (x, y) in ship_locations:
                    cell_state = ship_locations[(x, y)].get_position()
                else:
                    cell_state = CellState.EMPTY
                cell = {"x": x,
                        "y": y,
                        "cell_state": cell_state,
                        }
                row.append(cell)
            grid.append(row)
        return grid

    ####################################################################
    def get_player_grid(self, move, player):
        ship_locations = {(sl.x, sl.y): sl for sl in ShipLocation.objects.filter(ship__player=player, ship__game=move.game)}
        opponent = move.game.get_other_player(player)
        shots_this_move = Shot.objects.filter(move=move, player=opponent).values_list('x', 'y')
        shots_so_far = Shot.objects.filter(move__game=move.game, move__order__lte=move.order, player=opponent).values_list('x', 'y')

        grid = []
        for y in range(move.game.grid_height):
            row = []
            for x in range(move.game.grid_width):
                cell_state = self.get_cell_state(ship_locations, shots_this_move, shots_so_far, x, y)

                cell = {"x": x,
                        "y": y,
                        "cell_state": cell_state,
                        }
                row.append(cell)
            grid.append(row)
        return grid

    ####################################################################
    def get_cell_state(self, ship_locations, shots_this_move, shots_so_far, x, y):
        ship_location = ship_locations.get((x, y))

        if (x, y) in shots_this_move:
            if ship_location:
                return CellState.JUST_HIT
            else:
                return CellState.JUST_MISSED
        elif (x, y) in shots_so_far:
            if ship_location:
                return CellState.HIT
            else:
                return CellState.MISS
        else:
            if ship_location:
                return ship_location.get_position()
            else:
                return CellState.EMPTY

battleship_viewer/templates/battleship_viewer/base.html
<html>
<head>
<title>{% block title %}Battleship{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
    <p>
        <a href={% url 'home' %}>Home</a>
        <a href={% url 'list_games' %}>List Games</a>
    </p>
</body>
</html>

battleship_viewer/templates/battleship_viewer/game_detail.html
{% extends "battleship_viewer/base.html" %}

{% block content %}
    <h2>{{ game }}</h2>
    <p>
        Player1: {{ game.player1 }}<br />
        Player2: {{ game.player2 }}<br />
{#        Grid Size (w x h): {{ game.grid_width }} x {{ game.grid_height }}<br />#}
{#        Num Ships: {{ game.num_ships_per_player }}<br />#}
        Num Moves: {{ game.move_set.count }}<br />
        Num Shots: {{ game.num_shots }}<br />
        Winner: {{ game.winner }}
    </p>
    <p>
        <a href={% url 'list_moves' game.pk %}>List Moves</a>
    </p>
    <p>
        <a href={% url 'move-detail' game.pk 0 %}>Replay Game</a>
    </p>
{% endblock %}

battleship_viewer/templates/battleship_viewer/game_list.html
{% extends "battleship_viewer/base.html" %}

{% block content %}
    <h2>Games</h2>
    <ul>
        {% for game in game_list %}
{#            <li><a href={% url 'game-detail' game.pk %}>{{ game }}</a></li>#}
            <li><a href={% url 'move-detail' game.pk 0 %}>{{ game }}</a></li>
        {% empty %}
            <li>No Games Yet</li>
        {% endfor %}
    </ul>
{% endblock %}

battleship_viewer/templates/battleship_viewer/home.html
{% extends "battleship_viewer/base.html" %}

{% block content %}
    <h1>Battleship Viewer</h1>
    <a href={% url 'import_observer_log' %}>Import Observer Log</a>
    <br />
    <a href={% url 'list_games' %}>View Games</a>
{% endblock %}

battleship_viewer/templates/battleship_viewer/import_observer_log.html
{% extends "battleship_viewer/base.html" %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Import" />
    </form>
{% endblock %}

battleship_viewer/templates/battleship_viewer/move_detail.html
{% extends "battleship_viewer/base.html" %}
{% load static from staticfiles %}
{% load battleship_tags %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static "css/game_replay.css" %}">
    <h2>{{ move_label }}</h2>
    <div class="players">
    <div class="player player1">
    <h3 id="player1_name" class="player_name">{{ player1_name }}</h3>
    <table class="player player1">
        <tbody>
            {% for row in player1_grid %}
                <tr>
                    {% for cell in row %}
                        <td class="{{ cell.cell_state }}"></td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <p>{{ player2_shots }}&nbsp;</p>
    </div>
    <div class="player player2">
    <h3 id="player2_name" class="player_name">{{ player2_name }}</h3>
    <table class="player player2">
        <tbody>
            {% for row in player2_grid %}
                <tr>
                    {% for cell in row %}
                        <td class="{{ cell.cell_state }}"></td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <p>{{ player1_shots }}&nbsp;</p>
    </div>
    </div>
    <div style="clear:both;"></div>

    {% if not previous_move == None %}
        <a href="{% url 'move-detail' game.pk previous_move %}">Previous</a>
    {% else %}
        Previous
    {% endif %}
    {% if next_move %}
        <a href="{% url 'move-detail' game.pk next_move %}">Next</a>
    {% else %}
        Next
    {% endif %}
    <p>
        <a href="{% url 'game-detail' game.pk %}">Game Details</a>
    </p>
    <script type="text/javascript">
    function check_key(e)
    {
        {% if not previous_move == None %}
            if (e.keyCode == '37')
            {
                window.location = "{% url 'move-detail' game.pk previous_move %}";
            }
        {% endif %}
        {% if next_move %}
            if (e.keyCode == '39')
            {
                window.location = "{% url 'move-detail' game.pk next_move %}";
            }
        {% endif %}
    }
    document.onkeydown = check_key;
    </script>
{% endblock %}

battleship_viewer/templates/battleship_viewer/move_list.html
{% extends "battleship_viewer/base.html" %}

{% block content %}
    <h2>Moves for {{ game }}</h2>
    <ol>
            <li><a href={% url 'move-detail' game.pk 0 %}>Game Setup</a></li>
        {% for move in move_list %}
            <li><a href={% url 'move-detail' game.pk move.pk %}>{{ move }}</a>
            <ul>
            {% for shot in move.shot_set.all %}
                <li>{{ shot }}</li>
            {% empty %}
                <li>No Shots</li>
            {% endfor %}
            </ul>
            </li>
        {% empty %}
            <li>No Moves Yet</li>
        {% endfor %}
    </ol>
{% endblock %}